### ISSUE TITLE
The turtle file of the ontology does not have any domain and range definitions for the following properties

### ISSUE THREAD

**Issue by sumutcan** [perks-project/pk-ontology#3]
http://purl.org/dc/terms/created
http://purl.org/dc/terms/description
http://purl.org/dc/terms/identifier
http://purl.org/dc/terms/language
http://purl.org/dc/terms/modified
http://purl.org/dc/terms/title
http://www.w3.org/2006/time#numericDuration
http://www.w3.org/ns/dcat#accessURL
http://www.w3.org/ns/dcat#endDate
http://www.w3.org/ns/dcat#keyword
http://www.w3.org/ns/dcat#startDate
http://www.w3.org/ns/prov#atTime
http://www.w3.org/ns/prov#endedAtTime
http://www.w3.org/ns/prov#startedAtTime

https://w3id.org/pko#notesBySoftwareAgent
https://w3id.org/pko#notesByUser

http://purl.org/dc/terms/creator
http://purl.org/dc/terms/format
http://purl.org/dc/terms/references
http://purl.org/dc/terms/temporal
http://purl.org/net/p-plan#correspondsToVariable
http://purl.org/net/p-plan#hasInputVar
http://purl.org/net/p-plan#hasOutputVar
http://purl.org/net/p-plan#isStepOfPlan
http://purl.org/spar/pro/holdsRoleInTime
http://purl.org/spar/pro/relatesTo
http://purl.org/spar/pro/withRole
http://www.w3.org/2006/time#unitType
http://www.w3.org/ns/adms#status
http://www.w3.org/ns/dcat#hasCurrentVersion
http://www.w3.org/ns/dcat#hasVersion
http://www.w3.org/ns/dcat#isVersionOf
http://www.w3.org/ns/dcat#previousVersion
http://www.w3.org/ns/prov#used
http://www.w3.org/ns/prov#wasAssociatedWith
http://www.w3.org/ns/prov#wasGeneratedBy

https://w3id.org/pko#hasExpectedDuration

https://w3id.org/pko#hasStep

**Comment by sumutcan** [comment]
they do exist in the draw.io.

**Comment by marioscrock** [comment]
We do not want to enforce domain/range properties using RDFS for properties not defined by our ontology. For the ones defined by us, I kindly ask @valecarriero to check and provide feedback. 

Currently, we are documenting them via skos:scopeNote as "usage note" for the property in the context of our ontology. If you would need a machine readable representation maybe we can use dcam:domainIncludes/dcam:rangeIncludes or similar from Schema.org.

**Comment by sumutcan** [comment]
yeah I understand the motivation of that decision: in case the external ontology changes, you do not want to cause unintended inferences. but could be useful to have an informal domain range definition, as we would also need them for the shacl shapes. 
I sent you two CSV files where I completed the domain and ranges from the drawio diagram. I think it would be nice to add either dcam or schema.org primitives to indicate the domain and ranges "suggested" in our context.

**Comment by marioscrock** [comment]
I am attaching your CSV files here for reference 👍 
[classes.csv](https://github.com/user-attachments/files/17772372/classes.csv)
[properties.csv](https://github.com/user-attachments/files/17772373/properties.csv)

**Comment by valecarriero** [comment]
The two latest commits should have solved the issue
